### ISSUE TITLE
Plugin reports error: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by vaso123** [Haehnchen/idea-php-symfony2-plugin-doc#35]
From time to time I am getting the following error:

```
java.lang.IllegalArgumentException: Virtual file doesn't support id: LightVirtualFile: /activationResend.html.twig, implementation class: com.intellij.testFramework.LightVirtualFile
	at com.intellij.util.indexing.FileBasedIndex.getFileId(FileBasedIndex.java:71)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFileData(FileBasedIndexImpl.java:653)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigFileUtil.visitParentFiles(TwigFileUtil.java:63)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigFileUtil.collectParentFiles(TwigFileUtil.java:43)
	at fr.adrienbrault.idea.symfony2plugin.twig.loader.FileOverwritesLazyLoader.getFiles(FileOverwritesLazyLoader.java:46)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigBlockUtil.hasBlockOverwrites(TwigBlockUtil.java:149)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigLineMarkerProvider.attachBlockOverwrites(TwigLineMarkerProvider.java:283)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigLineMarkerProvider.collectSlowLineMarkers(TwigLineMarkerProvider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:194)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
What causes this?

**Comment by dstorozhuk** [comment]
Same issue.

**Comment by kevinpapst** [comment]
Getting the same issue multiple times a day. 
It is not always the same file, but always a twig file.
Anything we can do to help investigating the issue for this @Haehnchen ?
```
java.lang.IllegalArgumentException: Virtual file doesn't support id: LightVirtualFile: /permissions.html.twig, implementation class: com.intellij.testFramework.LightVirtualFile
	at com.intellij.util.indexing.FileBasedIndex.getFileId(FileBasedIndex.java:71)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFileData(FileBasedIndexImpl.java:653)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigFileUtil.visitParentFiles(TwigFileUtil.java:63)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigFileUtil.collectParentFiles(TwigFileUtil.java:43)
	at fr.adrienbrault.idea.symfony2plugin.twig.loader.FileOverwritesLazyLoader.getFiles(FileOverwritesLazyLoader.java:46)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigBlockUtil.hasBlockOverwrites(TwigBlockUtil.java:149)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigLineMarkerProvider.attachBlockOverwrites(TwigLineMarkerProvider.java:283)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigLineMarkerProvider.collectSlowLineMarkers(TwigLineMarkerProvider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:194)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by philoSurfer** [comment]
Bump... this is making day to day development with Twig files a PITA...

**Comment by kevinpapst** [comment]
Just found out that Google sent us to the wrong repository ;-)

Go and add your vote here: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1381
